apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnvrg
  namespace: argocd
spec:
  project: default
  source:
    chart: cnvrg
    repoURL: https://charts.v3.cnvrg.io
    targetRevision: 4.3.29
    helm:
      releaseName: cnvrg
      values: |
        clusterDomain: aws.dilerous.cloud
        controlPlane:
          baseConfig:
            featureFlags:
              CNVRG_ENABLE_MOUNT_FOLDERS: true
              CNVRG_MOUNT_HOST_FOLDERS: false
          image: cnvrg/app:v4.7.95
        dbs:
          es:
            storageSize: 10Gi
          minio:
            storageSize: 20Gi
          pg:
            storageSize: 20Gi
        logging:
          elastalert:
            enabled: false
        networking:
          ingress:
            type: ingress
          istio:
            enabled: false
            externalIp:
            - 172.31.21.239
        registry:
          password: ''
          user: ''
        capsule:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnvrg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
