apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnvrg
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cnvrg
      repoURL: https://charts.v3.cnvrg.io
      targetRevision: 4.3.30
      helm:
        releaseName: cnvrg
        valueFiles:
          - https://raw.githubusercontent.com/dilerous/argocd/main/cnvrg/values.yaml
    - repoURL: https://github.com/dilerous/argocd.git
      targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnvrg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
