apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnvrg
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cnvrg
      repoURL: https://github.com/dilerous/argocd
      targetRevision: 4.3.29
      helm:
        releaseName: cnvrg
        valueFiles:
          - cnvrg-values.yaml
    - repoURL: https://github.com/dilerous/argocd
      path: cnvrg
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnvrg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  syncStrategy:
    apply: true
