apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnvrg
  namespace: argocd
spec:
  project: default
  source:
    chart: cnvrg
    repoURL: https://charts.v3.cnvrg.io
    targetRevision: 4.3.29
    helm:
      releaseName: cnvrg
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnvrg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
