clusterDomain: worker.dilerous.cloud
controlPlane:
  baseConfig:
    featureFlags:
      CNVRG_ENABLE_MOUNT_FOLDERS: true
      CNVRG_MOUNT_HOST_FOLDERS: false
  image: cnvrg/app:v4.7.100
dbs:
  es:
    storageSize: 10Gi
  minio:
    storageSize: 20Gi
  pg:
    storageSize: 20Gi
monitoring:
  prometheus:
    storageSize: 10Gi
networking:
  ingress:
    type: ingress
  istio:
    enabled: false
    externalIp:
    - 172.31.21.239
registry:
  password: ''
  user: ''
capsule:
  enabled: false
sso:
  enabled: true
  provider: "oidc"
  emailDomain:
    - "*"
